name: build csi
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - app/csi/**
jobs:
  push:
    name: "docker:csi-${{ matrix.ver }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ver:
          - live
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./app/csi/${{ matrix.ver }}
          file: ./app/csi/${{ matrix.ver }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/damagex/docker:csi-${{ matrix.ver }}
