name: build debian
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - base/debian/**
jobs:
  push:
    name: "docker:debian-${{ matrix.os }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - bullseye
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./base/debian/${{ matrix.os }}
          file: ./images/debian/${{ matrix.os }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/damagex/docker:debian-${{ matrix.os }}
